-- [IX] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PRIMARY KEY 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE, -- UNIQUE : 유일, NULL 허용
    TEL VARCHAR2(20),
    LAST_MODIFYED DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NUM, NAME, PHONE) 
    VALUES (FRIEND_SEQ.NEXTVAL,'홍길동','010-9999-9999' );
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL,'홍길동',NULL,'02-716-1006' );
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL,'신길동','010-8888-8888','02-716-1006' );

INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, '김',NULL,NULL,SYSDATE);
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;

    
    


    
    
    
    
    
    

